// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQqAlExIiO0Nx9qnHDMnTLAZjjPJashfk',
    appId: '1:959768328108:web:6d5acdd1bc6e7d61932c09',
    messagingSenderId: '959768328108',
    projectId: 'car-rental-flutter-82704',
    authDomain: 'car-rental-flutter-82704.firebaseapp.com',
    storageBucket: 'car-rental-flutter-82704.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2B-aa3dtt196S19hYWRTcjNpivOBwa0',
    appId: '1:959768328108:android:52cfd3d3522d594c932c09',
    messagingSenderId: '959768328108',
    projectId: 'car-rental-flutter-82704',
    storageBucket: 'car-rental-flutter-82704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZIj9VKKNQHGx-gkoIwRECIzmcm8FLyb4',
    appId: '1:959768328108:ios:4210726e4bc7df60932c09',
    messagingSenderId: '959768328108',
    projectId: 'car-rental-flutter-82704',
    storageBucket: 'car-rental-flutter-82704.firebasestorage.app',
    iosBundleId: 'com.example.carRentalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZIj9VKKNQHGx-gkoIwRECIzmcm8FLyb4',
    appId: '1:959768328108:ios:4210726e4bc7df60932c09',
    messagingSenderId: '959768328108',
    projectId: 'car-rental-flutter-82704',
    storageBucket: 'car-rental-flutter-82704.firebasestorage.app',
    iosBundleId: 'com.example.carRentalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQqAlExIiO0Nx9qnHDMnTLAZjjPJashfk',
    appId: '1:959768328108:web:bacb7589eea695bc932c09',
    messagingSenderId: '959768328108',
    projectId: 'car-rental-flutter-82704',
    authDomain: 'car-rental-flutter-82704.firebaseapp.com',
    storageBucket: 'car-rental-flutter-82704.firebasestorage.app',
  );
}
